#spring.security.user.password=Demo@12345
jwt.secret=javainuse

# spring mvc path matching
#spring.mvc.pathmatch.matching-strategy=ant-path-matcher

# For logging 
#logging.file.name = app.log
logging.level.root=INFO
logging.config=classpath:logback.xml
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR
logging.level.net.guides=DEBUG

logging.file.path=C:/logs
